apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: home-nce-wtf
  namespace: external-dns
spec:
  endpoints:
    - dnsName: home.tb10.dpdns.org
      recordTTL: 300
      recordType: A
      targets:
        - 138.2.131.31
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: wildcard-home-nce-wtf
  namespace: external-dns
spec:
  endpoints:
    - dnsName: "*.home.tb10.dpdns.org"
      recordTTL: 300
      recordType: A
      targets:
        - 138.2.131.31
