apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      version: '9.2.10'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: grafana
  values:
    grafana.ini:
      app_mode: production
      server:
        domain: monitoring.tb10.dpdns.org
        root_url: https://monitoring.tb10.dpdns.org

      users:
        allow_sign_up: false

      auth:
        disable_login_form: true

      auth.generic_oauth:
        enabled: true
        name: Dex
        allow_sign_up: true
        client_id: $__file{/etc/secrets/dex_grafana_client/client-id}
        client_secret: $__file{/etc/secrets/dex_grafana_client/client-secret}
        scopes: openid profile email groups
        ;empty_scopes: false
        email_attribute_path: email
        ;id_token_attribute_name:
        auth_url: https://login.tb10.dpdns.org/dex/auth
        token_url: https://login.tb10.dpdns.org/dex/token
        api_url: https://login.tb10.dpdns.org/dex/userinfo
        role_attribute_path: contains(groups[*], 'tb10-org:Admin') && 'Admin' || 'Viewer'

    extraSecretMounts:
      - name: dex-grafana-client
        secretName: dex-grafana-client
        defaultMode: 0440
        mountPath: /etc/secrets/dex_grafana_client
        readOnly: true

    plugins:
      - oci-metrics-datasource

    ingress:
      enabled: true
      hosts:
        - monitoring.tb10.dpdns.org
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        #nginx.ingress.kubernetes.io/limit-connections: "10"
        #nginx.ingress.kubernetes.io/limit-rps: "100"
        external-dns.alpha.kubernetes.io/hostname: monitoring.tb10.dpdns.org
      tls:
        - hosts:
            - monitoring.tb10.dpdns.org
          secretName: grafana-cert
    sidecar:
      dashboards:
        enabled: true
        logLevel: INFO
        searchNamespace: grafana
        label: grafana_dashboard
      datasources:
        enabled: true
        searchNamespace: grafana
