apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-token
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: receiver-token
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: github-flux-webhook-token
        version: CURRENT
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluxcd-github-token
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: fluxcd-github-token
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: github-fluxcd-token
        version: CURRENT
---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: fluxcd-slack-webhook
# spec:
#   refreshInterval: 3m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: oracle-vault
#   target:
#     name: fluxcd-slack-webhook
#     creationPolicy: Owner
#     deletionPolicy: Delete
#     template:
#       engineVersion: v2
#       data:
#         token: "{{ .token }}"
#   data:
#     - secretKey: token
#       remoteRef:
#         key: slack-fluxcd-token
#         version: CURRENT
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-grafana-client
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-grafana-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        client-id: grafana
        client-secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-grafana-client
        version: CURRENT
        decodingStrategy: None